35 implement basic column masking
nadavgross/trino-opa-example pull request #60
Opened 2024-01-22 15:53 UTC by TamKez

Added row level filtering that works with the api.
The rule goes over the different attributes that are relevant in the user and table, and when the table requires rls, and the user's attribute is relevent for the tables content worls, rls policies are created.

2024-01-22 16:09 UTC, shohamyamin requested changes
fix according to the feedback

2024-01-22 16:09 UTC, shohamyamin commented on opa/policies/cms/README.md
>  # CMS (Column Masking Security) Package
Add explanation about how the attribute affect column masking

2024-01-22 16:09 UTC, shohamyamin commented on opa/policies/rls/README.md
> +
Add explanation about how the row level attributes are used in the rls rules

2024-01-22 16:09 UTC, shohamyamin commented on opa/policies/rls/rls.rego
> +	expression := sprintf("%v <> %v", [filter_feild, filter_value])
Change the sql expression to be `nationKey in (1,2,3,4)`

change the misspelling feild to field

2024-01-25 14:19 UTC, shohamyamin approved these changes

2024-01-25 14:20 UTC, shohamyamin approved these changes
looks good

2024-01-25 14:22 UTC, shohamyamin approved these changes
looks wonderful!!

2024-01-25 14:27 UTC, nadavgross approved these changes
nice

2024-01-25 14:27 UTC, merged